name: Code Quality Checks

on:
  push:
    branches: [main]
  pull_request:

jobs:
  code_quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install Node.js Dependencies
        run: npm install

      - name: Set Up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          tools: composer
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Get Modified Files
        id: changed_files
        run: |
          echo "FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_ENV

      - name: Run Prettier (JS, Blade, etc.)
        if: env.FILES != ''
        run: npx prettier --write $FILES

      - name: Run Duster (includes Pint + more)
        if: env.FILES != ''
        run: |
          ./vendor/bin/duster fix $FILES
          ./vendor/bin/duster lint $FILES

      - name: Auto Commit Fixes
        if: env.FILES != ''
        id: auto_commit
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Apply automated code quality fixes"
          commit_user_name: "GitHub Action"
          commit_user_email: "actions@github.com"

      - name: Add Auto-Fix Commit to .git-blame-ignore-revs
        if: env.FILES != ''
        run: echo "${{ steps.auto_commit.outputs.commit_hash }}" >> .git-blame-ignore-revs
        continue-on-error: true

      - name: Commit .git-blame-ignore-revs Update
        if: env.FILES != ''
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "Update .git-blame-ignore-revs with formatting commit"
          commit_user_name: "GitHub Action"
          commit_user_email: "actions@github.com"
