name: Prettier Code Formatting

on:
    push:
        branches: [main]
    pull_request:

jobs:
    prettier:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Set Up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'

            - name: Install Node.js Dependencies
              run: npm install

            - name: Get Modified Files
              id: changed_files
              run: echo "FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep -E '\.blade\.php$' | xargs)" >> $GITHUB_ENV

            - name: Run Prettier on Modified Blade Files
              if: env.FILES != ''
              run: npx prettier --write $FILES

            - name: Auto Commit Fixes
              if: env.FILES != ''
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: 'Apply Prettier formatting'
                  commit_user_name: 'GitHub Action'
                  commit_user_email: 'actions@github.com'
